version: '3.7'
services:
  frontend:
    image: ghcr.id/dbswndk/personal-project-frontend:latest
    container_name: personal-project-frontend
    networks:
      - app

networks:
  app:
    driver: bridge