version: "3.7"
services:
  services:
    frontend:
      image: ghcr.io/cjw0824/frontend-server:latest
      container_name: docker-frontend-deploy-server
      networks:
        - app

networks:
  app:
    driver: bridge